export * from './render.component';
export * from './text.component';
export * from './position.component';
export * from './size.component';
export * from './interactiveComponent';
export * from './answer.component';
export * from './input.component';
export * from './button.component';
export * from './html-element.component';
